Repository Graylog2/collector-sidecar, pull requests merged in 2018-09, with the labels that each got.

#281 Make overall Sidecar status more explicit
  api/graylog.go
  services/periodicals.go
Labels: ready-for-review

#286 Fix missing whitelist check
  backends/backend.go
  backends/render.go
  daemon/exec_runner.go
  daemon/svc_runner_windows.go
  services/periodicals.go
Labels: ready-for-review

#293 Fix more default paths
  dist/recipe.rb
  dist/recipe32.rb
  sidecar-windows-example.yml
Labels: ready-for-review

#292 Use checksum for config render requests
  daemon/daemon.go
  services/periodicals.go
Labels: ready-for-review

#294 Add special commandline parsing for Windows
  backends/backend.go
  common/exec_helper.go
  common/exec_helper_windows.go
Labels: bug, ready-for-review

#295 Have the Windows installer ask for the API token
  README.md
  dist/recipe.nsi
  sidecar-windows-example.yml
Labels: enhancement, ready-for-review
