Repository Graylog2/collector-sidecar, pull requests merged in 2019-03, with the labels that each got.

#347 Default the windows installer to an empty nodename
  dist/recipe.nsi
Labels: improvement, ready-for-review

#351 Include example configurations in tar-ball
  Makefile
Labels: ready-for-review

#353 Wipe configchecksums also on assignment changes
  assignments/assignment.go
  daemon/daemon.go
  services/periodicals.go
Labels: backport, ready-for-review
